using Akar.Domain.Common;

namespace Akar.Domain.Entities;

/// <summary>
/// A secure upload link generated by the owner for a project follower.
/// Only the token hash is stored; the raw token is returned once at creation.
/// Public callers use the raw token to upload files into the follower's inbox folder.
/// </summary>
public class FollowerUploadLink : Entity<Guid>
{
    public Guid ProjectId { get; private set; }
    public Guid OwnerId { get; private set; }
    public Guid FollowerId { get; private set; }
    public string TokenHash { get; private set; } = string.Empty;
    public string? TokenPreview { get; private set; }
    public DateTime? ExpiresAtUtc { get; private set; }
    public bool IsActive { get; private set; }
    public bool IsRevoked { get; private set; }
    public DateTime? RevokedAtUtc { get; private set; }
    public DateTime? LastUsedAtUtc { get; private set; }

    // Navigation
    public Project Project { get; private set; } = null!;
    public Owner Owner { get; private set; } = null!;
    public ProjectFollower Follower { get; private set; } = null!;

    private FollowerUploadLink() { } // EF Core

    public static FollowerUploadLink Create(
        Guid projectId,
        Guid ownerId,
        Guid followerId,
        string tokenHash,
        string? tokenPreview,
        DateTime? expiresAtUtc)
    {
        return new FollowerUploadLink(Guid.NewGuid())
        {
            ProjectId = projectId,
            OwnerId = ownerId,
            FollowerId = followerId,
            TokenHash = tokenHash,
            TokenPreview = tokenPreview,
            ExpiresAtUtc = expiresAtUtc,
            IsActive = true,
            IsRevoked = false
        };
    }

    /// <summary>Revokes this upload link.</summary>
    public bool Revoke()
    {
        if (IsRevoked) return false;
        IsRevoked = true;
        IsActive = false;
        RevokedAtUtc = DateTime.UtcNow;
        SetUpdatedAt();
        return true;
    }

    /// <summary>Records the last time this link was used for an upload.</summary>
    public void RecordUsage()
    {
        LastUsedAtUtc = DateTime.UtcNow;
        SetUpdatedAt();
    }

    /// <summary>Whether the link is currently valid for use.</summary>
    public bool IsValidForUse()
    {
        if (!IsActive || IsRevoked) return false;
        if (ExpiresAtUtc.HasValue && ExpiresAtUtc.Value < DateTime.UtcNow) return false;
        return true;
    }

    private FollowerUploadLink(Guid id) : base(id) { }
}
